package com.kan;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
public class LionspriveTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lionsprive() throws InterruptedException {
    // Test name: lions prive
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.wildberries.ru/");
    // 2 | setWindowSize | 1552x840 | 
    driver.manage().window().maximize();
    Thread.sleep(2000);
    // 3 | type | id=tbSrch | lio
    driver.findElement(By.id("tbSrch")).click();
    // 5 | type | id=tbSrch | lions prive
    driver.findElement(By.id("tbSrch")).sendKeys("lions prive");
    // 6 | sendKeys | id=tbSrch | ${KEY_ENTER}
    driver.findElement(By.id("tbSrch")).sendKeys(Keys.ENTER);
    // 7 | click | css=#c14795817 > .thumbnail | 
    driver.findElement(By.id("c14795818")).click();
    // 8 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 9 | click | css=.j-add-to-card | 
    driver.findElement(By.cssSelector(".j-add-to-card")).click();
    // 10 | click | css=.color:nth-child(2) img | 
    driver.findElement(By.cssSelector(".color:nth-child(2) img")).click();
    // 11 | click | css=.j-add-to-card | 
    driver.findElement(By.cssSelector(".j-add-to-card")).click();
    // 12 | click | css=.color:nth-child(3) img | 
    driver.findElement(By.cssSelector(".color:nth-child(3) img")).click();
    // 13 | mouseOver | css=.j-add-to-card | 
    {
      WebElement element = driver.findElement(By.cssSelector(".j-add-to-card"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | click | css=.j-add-to-card | 
    driver.findElement(By.cssSelector(".j-add-to-card")).click();
    // 15 | click | css=.color:nth-child(4) img | 
    driver.findElement(By.cssSelector(".color:nth-child(4) img")).click();
    // 16 | click | css=.j-add-to-card | 
    driver.findElement(By.cssSelector(".j-add-to-card")).click();
    // 17 | click | css=.color:nth-child(5) img | 
    driver.findElement(By.cssSelector(".color:nth-child(5) img")).click();
    // 18 | mouseOver | css=.color:nth-child(5) img | 
    {
      WebElement element = driver.findElement(By.cssSelector(".color:nth-child(5) img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | mouseOut | css=.color:nth-child(5) img | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 20 | click | css=.j-add-to-wait | 
    driver.findElement(By.cssSelector(".j-add-to-wait")).click();
    // 21 | mouseOut | css=.j-add-to-card | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
