package com.kan;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.File;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WilupTest extends WebDriverException {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void wilup() throws InterruptedException {
    // Test name: wilup
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("https://suppliers.wildberries.ru/login");
    // 2 | setWindowSize | 1552x840 | 
    driver.manage().window().setSize(new Dimension(1552, 840));
    // 3 | click | name=email_or_login | 
    driver.findElement(By.name("email_or_login")).click();
    // 4 | type | name=email_or_login | supp102092
    driver.findElement(By.name("email_or_login")).sendKeys("supp102092");
    // 5 | click | css=.login-form | 
    driver.findElement(By.cssSelector(".login-form")).click();
    // 6 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 7 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 8 | type | name=password | b352d5EK
    driver.findElement(By.name("password")).sendKeys("b352d5EK");
    // 9 | click | css=.login-form_button | 
    driver.findElement(By.cssSelector(".login-form_button")).click();
    Thread.sleep(2000);
    // 10 | click | css=.wbpa-menu__section:nth-child(3) .wbpa-menu__section_item:nth-child(4) > .wbpa-menu__section_url | 
    driver.findElement(By.cssSelector(".wbpa-menu__section:nth-child(3) .wbpa-menu__section_item:nth-child(4) > .wbpa-menu__section_url")).click();
    // 11 | click | css=.wbpa-menu__section:nth-child(3) .wbpa-menu__section_item:nth-child(4) a:nth-child(1) > li | 
    driver.findElement(By.cssSelector(".wbpa-menu__section:nth-child(3) .wbpa-menu__section_item:nth-child(4) a:nth-child(1) > li")).click();
    // 12 | mouseOver | css=.excel-button | 
    {
      WebElement element = driver.findElement(By.cssSelector(".excel-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 13 | mouseOut | css=.excel-button | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    Thread.sleep(3000);
    driver.findElement(By.cssSelector(".file-draggable")).sendKeys("C:/Users/User/Downloads/Otchet (6).xlsx");
   Thread.sleep(5000);

    // 16 | click | css=span:nth-child(1) |
    driver.findElement(By.cssSelector("span:nth-child(1)")).click();
    Thread.sleep(10000);
  }
}
